"""
Name:  James Michael Crespo
Email: james.crespo64@myhunter.cuny.edu
Resources: the internet
"""
import pickle
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures


def clean_reg(reg):
    """
    If reg is passenger 'PAS' or commercial 'COM', return those values. Otherwise, return 'OTHER'.

    :param reg: a string containing the registration status of the vehicle.
    """
    if (reg == 'PAS') or (reg == 'COM'):
        return reg
    else:
        return 'OTHER'


def clean_color(col):
    """
    takes a string, and replaces to a value based on input, if not a value, change to other

    :param col: a string containing the color of the vehicle.
    """
    if col.upper() in ['GY', 'GRAY', 'GREY', 'SILVE', ' SIL', 'SL']:
        return 'GRAY'
    elif col.upper() in ['WH', 'WHITE']:
        return 'WHITE'
    elif col.upper() in ['BK', 'BLACK', 'BL']:
        return 'BLACK'
    elif col.upper() in ['BLUE']:
        return 'BLUE'
    elif col.upper() in ['RED', 'RD']:
        return 'RED'
    elif col.upper() in ['GR', 'GREEN']:
        return 'GREEN'
    elif col.upper() in ['BROWN', 'TAN']:
        return 'BROWN'
    else:
        return 'OTHER'


def add_indicators(df, cols=['Registration', 'Color', 'State']):
    """
    Returns df with additional indicator col generated by get_dummies for specified columns. 
    The drop_first flag is set to True to drop extraneous columns.

    :param df: a DataFrame that including the columns specified in cols.
    :param col: a list of names of cols in df. default = ['Registration', 'Color', 'State'].
    """
